package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Build {
  private String name;
  private String group;
  private String version;
  private List<Method> methods;
  private List<Dependency> dependencies;
  private List<Repository> repositories;
  private List<Plugin> plugins;



  public Build(String name, String group, String version) {
    this.name = name;
    this.group = group;
    this.version = version;
    this.methods = ListSequence.fromListAndArray(new ArrayList<Method>(), new Method("Method1"));
    this.dependencies = ListSequence.fromListAndArray(new ArrayList<Dependency>(), new Dependency("Dep1", "1"));
    this.repositories = ListSequence.fromListAndArray(new ArrayList<Repository>(), new Repository("Repo1"));
    this.plugins = ListSequence.fromListAndArray(new ArrayList<Plugin>(), new Plugin("1", "Plugin1", "Plg1"));
  }



  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public String getVersion() {
    return this.version;
  }
  public void setVersion(String version) {
    this.version = version;
  }
  public String getGroup() {
    return this.group;
  }
  public void setGroup(String group) {
    this.group = group;
  }
}
