package MPS.sandbox.C_Model;

/*Generated by MPS */


public class Dependency {
  private String name;
  private String version;


  public Dependency(String name, String version) {
    this.name = name;
    this.version = version;
  }
}
