package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import java.util.Scanner;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Rule {
  private String name;
  private List<Command> commands;
  private List<File> targets;

  public Scanner scanner = new Scanner(System.in);

  public Rule(String name) {
    this.name = name;
    this.commands = ListSequence.fromListAndArray(new ArrayList<Command>(), new Command("Delete"));
    this.targets = ListSequence.fromListAndArray(new ArrayList<File>(), new File("Filename1"));


  }

  public void exec() {
    System.out.println("Rule" + "Rule1" + ":");

    Integer option = -1;
    System.out.println("\nList of Commands");

    while (option != 0) {
      int index = 2;
      for (Command c : commands) {
        System.out.format("%d - %s", index, c.getName());
        index++;
      }
      System.out.println("0 - Exit");
      System.out.print("\n Choose an option: ");
      option = scanner.nextInt();

      if (option != 0) {
        System.out.println("Invalid Option!");
      }
    }
  }

}
