package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class C_Model {
  private List<Project> projects = ListSequence.fromList(new ArrayList<Project>(0));
  private List<Rule> rules = ListSequence.fromList(new ArrayList<Rule>(0));


  public C_Model() {
    // Projects
    ListSequence.fromList(this.projects).addElement(new Project("Cproject", "1"));

    // Rules
    ListSequence.fromList(this.rules).addElement(new Rule("Rule1"));

  }

  public void exec() {
    System.out.println("C_Model");

    for (Project project : ListSequence.fromList(this.projects)) {
      project.exec();
    }

    for (Rule rule : ListSequence.fromList(this.rules)) {
      rule.exec();
    }

  }
}
