package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class File {
  private String filename;
  private List<Function> functions;

  public File(String filename) {
    this.filename = filename;
    this.functions = ListSequence.fromListAndArray(new ArrayList<Function>(), new Function("Func1", "argv"));
  }
}
