package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import java.util.Scanner;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Project {
  private String name;
  private String version;
  private List<Property> properties;
  private List<Parameters> attributes;
  private List<Build> builds;
  private List<Task> tasks;

  public Scanner scanner = new Scanner(System.in);

  public Project(String name, String version) {
    this.name = name;
    this.version = version;
    this.properties = ListSequence.fromListAndArray(new ArrayList<Property>(), new Property("Prop1", "1"));
    this.attributes = ListSequence.fromListAndArray(new ArrayList<Parameters>(), new Parameters("Argv", "1"));
    this.builds = ListSequence.fromListAndArray(new ArrayList<Build>(), new Build("Build1", "c.group.build", "1"));
    this.tasks = ListSequence.fromListAndArray(new ArrayList<Task>(), new Task("Task1", "Task1_desc", "c.group", "false"));
  }

  public void exec() {
    System.out.println("Project" + "Cproject" + ":");
    System.out.println("\t version:" + "1");

    Integer option = -1;
    System.out.println("\nList of Builds");

    while (option != 0) {
      int index = 2;
      for (Build b : builds) {
        System.out.format("%d - %s", index, b.getName());
        index++;
      }
      System.out.println("0 - Exit");
      System.out.print("\n Choose an option: ");
      option = scanner.nextInt();

      if (option != 0) {
        System.out.println("Invalid Option!");
      }
    }
  }

}
