package MPS.sandbox.C_Model;

/*Generated by MPS */


public class Property {
  private String Prop1;
  private Parameters attribute;


  public Property(String name, String value) {
    this.Prop1 = "Prop1";
    this.attribute = new Parameters(name, value);
  }

}
