package MPS.sandbox.C_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Task {
  private String name;
  private String description;
  private String group;
  private Boolean enable = false;

  private List<Action> actions;



  public Task(String name, String description, String group, String enable) {
    this.name = "Task1";
    this.description = "Task1_desc";
    this.group = "c.group";
    if ((enable != null && enable.length() > 0)) {
      this.enable = Boolean.valueOf(enable);
    }

    this.actions = ListSequence.fromListAndArray(new ArrayList<Action>(), new Action("Action1", "action_desc", "Awesome_action"));

  }

}
