package MPS.sandbox.Java_Model;

/*Generated by MPS */


public class Action {
  private String name;
  private String description;
  private String type;


  public Action(String name, String description, String type) {
    this.name = name;
    this.description = description;
    this.type = type;
  }
}
