package MPS.sandbox.Java_Model;

/*Generated by MPS */


public class Command {
  private String name;
  private Prefix prefix;

  public Command(String name) {
    this.name = name;
    this.prefix = new Prefix("Del");
  }

  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
}
