package MPS.sandbox.Java_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class File {
  private String filename;
  private List<Function> functions;
  private List<Parameters> attributes;

  public File(String filename) {
    this.filename = filename;
    this.functions = ListSequence.fromListAndArray(new ArrayList<Function>(), new Function("Function1", "argv"));
    this.attributes = ListSequence.fromListAndArray(new ArrayList<Parameters>(), new Parameters("Parameter1", "1"));
  }
}
