package MPS.sandbox.Java_Model;

/*Generated by MPS */


public class Parameters {
  private String name;
  private String value;

  public Parameters(String name, String value) {
    this.name = name;
    this.value = value;
  }
  public Parameters() {
  }



}
