package MPS.sandbox.Java_Model;

/*Generated by MPS */


public class Plugin {
  private String id;
  private String name;
  private String type;


  public Plugin(String id, String name, String type) {
    this.id = id;
    this.name = name;
    this.type = type;
  }
}
