package MPS.sandbox.Java_Model;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Task {
  private String name;
  private String description;
  private String group;
  private Boolean enable = false;
  private Script scripts;

  private List<Action> actions;
  private List<Parameters> attributes;



  public Task(String name, String description, String group, String enable) {
    this.name = "Compile";
    this.description = "Compile task";
    this.group = "java.group";
    if ((enable != null && enable.length() > 0)) {
      this.enable = Boolean.valueOf(enable);
    }
    this.scripts = new Script("Script1");

    this.actions = ListSequence.fromListAndArray(new ArrayList<Action>(), new Action("Action1", "this is action 1", "Action type"));
    this.attributes = ListSequence.fromListAndArray(new ArrayList<Parameters>(), new Parameters("Argv", "compile"));

  }

}
