package MPS.sandbox.Model;

/*Generated by MPS */


public class Function {
  private String name;
  private String variables;


  public Function(String name, String variables) {
    this.name = name;
    this.variables = variables;
  }
}
