package MPS.sandbox.Model;

/*Generated by MPS */


public class Task {
  private String name;
  private String description;
  private String group;
  private Boolean enable = false;




  public Task(String name, String description, String group, String enable) {
    this.name = "Task1";
    this.description = "desc";
    this.group = "model.group";
    if ((enable != null && enable.length() > 0)) {
      this.enable = Boolean.valueOf(enable);
    }


  }

}
