# Use the official MongoDB image as the base image
FROM mongo:latest

# Optionally, set environment variables
# ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=yourpassword

# Optionally, expose MongoDB port (27017 by default)
# EXPOSE 27017

# Optionally, create a working directory
# WORKDIR /app

# Optionally, copy your MongoDB configuration files to the container
# COPY mongo.conf /etc/mongo/mongo.conf

# Start the MongoDB server
CMD ["mongod"]
