package MPS.sandbox.Java_Model;

/*Generated by MPS */


public class Property {
  private String Property1;
  private Parameters attribute;


  public Property(String name, String value) {
    this.Property1 = "Property1";
    this.attribute = new Parameters(name, value);
  }

}
